
// TODO make it dynamic
export const sectors = [
  // Categorized by Office
    {name: "Planning Office", id: "planning"},
    {name: "Office of the Assistant Director for Academic Affairs", id: "adaa"},
    {name: "Quality Assurance / ISO", id: "qa"},
    {name: "GAD", id: "gad"},
    {name: "UITC", id: "uitc"},
    {name: "Office of the Assistant Director for Admin and Finance", id: "adaf"},
    {name: "Human Resource Management Department", id: "hrmd"},
    {name: "Accounting Office ", id: "accounting"},
    {name: "Collecting and Disbursing Office", id: "cdo"},
    {name: "Records Office", id: "records"},
    {name: "Procurement Office", id: "procurement"},
    {name: "Property and Supply Office", id: "supply"},
    {name: "Infrastructure and Development Office", id: "ido"},
    {name: "Building and Grounds Maintenance", id: "bgm"},
    {name: "Electrical Maintenance", id: "electrical"},
    {name: "HVACR Maintenance", id: "hvacr"},
    {name: "Medical Clinic", id: "medical"},
    {name: "Dental Clinic", id: "dental"},
    {name: "Bids and Awards Committee", id: "bac"},
    {name: "Basic Arts and Sciences Department", id: "basd"},
    {name: "BTVTE", id: "btvte"},
    {name: "Civil and Allied Department", id: "caad"},
    {name: "BSES", id: "bses"},
    {name: "BSCE", id: "bsce"},
    {name: "BETCT", id: "betct"},
    {name: "BETCHET", id: "betchet"},
    {name: "Mechanical and Allied Department", id: "maad"},
    {name: "BSME", id: "bsme"},
    {name: "BETMT", id: "betmt"},
    {name: "BETDMT", id: "betdmt"},
    {name: "BETNDT", id: "betndt"},
    {name: "BETEMET", id: "betemet"},
    {name: "BETHVACR", id: "bethvacr"},
    {name: "BETAT", id: "betat"},
    {name: "Electrical and Allied Department ", id: "eaad"},
    {name: "BSEE", id: "bsee"},
    {name: "BSCE", id: "bsce"},
    {name: "BSIT", id: "bsit"},
    {name: "BETET", id: "betet"},
    {name: "BETELEX", id: "betelex"},
    {name: "BETICT", id: "betict"},
    {name: "BETMECT", id: "betmect"},
    {name: "Office of Student Affairs", id: "osa"},
    {name: "Registration and Admission Office", id: "registrar"},
    {name: "Library", id: "library"},
    {name: "Guidance Office", id: "guidance"},
    {name: "Sports and Cultural Dev't", id: "sports"},
    {name: "NSTP/ROTC", id: "nstp"},
    {name: "Industry Based Program", id: "industry"},
    {name: "USG", id: "usg"},
    {name: "Artisan", id: "artisan"},
    {name: "Office of the Assistant Director for Research and Extension", id: "adre"},
    {name: "Research", id: "research"},

  ]